version: '3'

networks:
  microservices:
    external: true


services:

  user-service-api:
    image: assignment123/user-service
    build:
      context: ../../..
      dockerfile: _config/docker/image/Dockerfile

    container_name: user-service-api
    hostname: user-service-api
#    command: "/scripts/run-java.sh"
#    volumes:
#      -
    ports:
      - 8080:8080

    networks:
      - microservices

    env_file:
      - "../env/development.env"
